name: Deploy Node.js app to Azure Web App

on:
  push:
    branches: [ "main" ]     
    
env:
  AZURE_WEBAPP_NAME: 'project3-app-thato'
  NODE_VERSION: '24.x' 
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        cache: 'npm'

    - name: Check package.json
      run: |
       ls -la
       cat package.json || echo "No package.json found!"


    - name: Install dependencies
      run: npm install

    - name: Build (if needed)
      run: npm run build --if-present

    - name: List files for debugging
      run: find . -name "*.js" | head -10
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: 'avengersai.azurewebsites.net'

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AvengersAI'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISHPROFILE }}
       


